<?xml version="1.0" encoding="utf-8"?><Database Name="TTCM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HT0NP1M;Initial Catalog=TTCM;Integrated Security=True" SettingsObjectName="QLCH.Properties.Settings" SettingsPropertyName="TTCMConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chiTietHDN" Member="chiTietHDNs">
    <Type Name="chiTietHDN">
      <Column Name="maHDN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="sanPham_chiTietHDN" Member="sanPham" ThisKey="maSP" OtherKey="maSP" Type="sanPham" IsForeignKey="true" />
      <Association Name="hoadDonNhap_chiTietHDN" Member="hoadDonNhap" ThisKey="maHDN" OtherKey="maHDN" Type="hoadDonNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sanPham" Member="sanPhams">
    <Type Name="sanPham">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thongSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="sanPham_chiTietHDN" Member="chiTietHDNs" ThisKey="maSP" OtherKey="maSP" Type="chiTietHDN" />
      <Association Name="sanPham_chiTietHDX" Member="chiTietHDXes" ThisKey="maSP" OtherKey="maSP" Type="chiTietHDX" />
      <Association Name="sanPham_chiTietSP" Member="chiTietSPs" ThisKey="maSP" OtherKey="maSP" Type="chiTietSP" />
      <Association Name="HangSP_sanPham" Member="HangSP" ThisKey="maHang" OtherKey="maHang" Type="HangSP" IsForeignKey="true" />
      <Association Name="nhomSP_sanPham" Member="nhomSP" ThisKey="maLoai" OtherKey="maLoai" Type="nhomSP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chiTietHDX" Member="chiTietHDXes">
    <Type Name="chiTietHDX">
      <Column Name="maHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="sanPham_chiTietHDX" Member="sanPham" ThisKey="maSP" OtherKey="maSP" Type="sanPham" IsForeignKey="true" />
      <Association Name="hoadDonXuat_chiTietHDX" Member="hoadDonXuat" ThisKey="maHDX" OtherKey="maHDX" Type="hoadDonXuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chiTietSP" Member="chiTietSPs">
    <Type Name="chiTietSP">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soSerial" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="sanPham_chiTietSP" Member="sanPham" ThisKey="maSP" OtherKey="maSP" Type="sanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.congViec" Member="congViecs">
    <Type Name="congViec">
      <Column Name="maCV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bacLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="congViec_nhanVien" Member="nhanViens" ThisKey="maCV" OtherKey="maCV" Type="nhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.CTGio" Member="CTGios">
    <Type Name="CTGio">
      <Column Name="maCTG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="magio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuNhap" Member="CTPhieuNhaps">
    <Type Name="CTPhieuNhap">
      <Column Name="maphieu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masp" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sl" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GioHang" Member="GioHangs">
    <Type Name="GioHang">
      <Column Name="magio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="makh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangSP" Member="HangSPs">
    <Type Name="HangSP">
      <Column Name="maHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HangSP_sanPham" Member="sanPhams" ThisKey="maHang" OtherKey="maHang" Type="sanPham" />
    </Type>
  </Table>
  <Table Name="dbo.hoadDonNhap" Member="hoadDonNhaps">
    <Type Name="hoadDonNhap">
      <Column Name="maHDN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="hoadDonNhap_chiTietHDN" Member="chiTietHDNs" ThisKey="maHDN" OtherKey="maHDN" Type="chiTietHDN" />
      <Association Name="nhaCungCap_hoadDonNhap" Member="nhaCungCap" ThisKey="maNCC" OtherKey="maNCC" Type="nhaCungCap" IsForeignKey="true" />
      <Association Name="nhanVien_hoadDonNhap" Member="nhanVien" ThisKey="maNV" OtherKey="maNV" Type="nhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hoadDonXuat" Member="hoadDonXuats">
    <Type Name="hoadDonXuat">
      <Column Name="maHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="hoadDonXuat_chiTietHDX" Member="chiTietHDXes" ThisKey="maHDX" OtherKey="maHDX" Type="chiTietHDX" />
      <Association Name="khachHang_hoadDonXuat" Member="khachHang" ThisKey="maKH" OtherKey="maKH" Type="khachHang" IsForeignKey="true" />
      <Association Name="nhanVien_hoadDonXuat" Member="nhanVien" ThisKey="maNV" OtherKey="maNV" Type="nhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khachHang" Member="khachHangs">
    <Type Name="khachHang">
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="khachHang_hoadDonXuat" Member="hoadDonXuats" ThisKey="maKH" OtherKey="maKH" Type="hoadDonXuat" />
    </Type>
  </Table>
  <Table Name="dbo.nhaCungCap" Member="nhaCungCaps">
    <Type Name="nhaCungCap">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="nhaCungCap_hoadDonNhap" Member="hoadDonNhaps" ThisKey="maNCC" OtherKey="maNCC" Type="hoadDonNhap" />
    </Type>
  </Table>
  <Table Name="dbo.nhanVien" Member="nhanViens">
    <Type Name="nhanVien">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWords" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="nhanVien_hoadDonNhap" Member="hoadDonNhaps" ThisKey="maNV" OtherKey="maNV" Type="hoadDonNhap" />
      <Association Name="nhanVien_hoadDonXuat" Member="hoadDonXuats" ThisKey="maNV" OtherKey="maNV" Type="hoadDonXuat" />
      <Association Name="congViec_nhanVien" Member="congViec" ThisKey="maCV" OtherKey="maCV" Type="congViec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhomSP" Member="nhomSPs">
    <Type Name="nhomSP">
      <Column Name="maLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="nhomSP_sanPham" Member="sanPhams" ThisKey="maLoai" OtherKey="maLoai" Type="sanPham" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="maphieu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="manv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngLapPhieu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ACC_Add" Method="ACC_Add">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dn" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateSP" Method="updateSP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Double" DbType="Float" />
    <Parameter Name="anh" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="maLoai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maHang" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ACC_Del" Method="ACC_Del">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ACC_DelResult">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWords" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ACC_FindID" Method="ACC_FindID">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ACC_FindIDResult">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ACC_FindTenDN" Method="ACC_FindTenDN">
    <Parameter Name="tdn" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ACC_FindTenDNResult">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ACC_Sel" Method="ACC_Sel">
    <ElementType Name="ACC_SelResult">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ACC_Up" Method="ACC_Up">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addSP" Method="addSP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Double" DbType="Float" />
    <Parameter Name="anh" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thongSo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maLoai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maHang" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.bill_search" Method="bill_search">
    <Parameter Name="a" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="bill_searchResult">
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.cthdx_insert" Method="cthdx_insert">
    <Parameter Name="maHDX" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="donGia" Type="System.Double" DbType="Float" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thanhTien" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delete_CTcart" Method="delete_CTcart">
    <Parameter Name="maCTG" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteSP" Method="deleteSP">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.hdx_select" Method="hdx_select">
    <ElementType Name="hdx_selectResult">
      <Column Name="maHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maKH1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maNV1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWords" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.insert_cart" Method="insert_cart">
    <Parameter Name="maGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="donGia" Type="System.Double" DbType="Float" />
    <Parameter Name="thanhTien" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_gioHang" Method="insert_gioHang">
    <Parameter Name="maKh" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KH_Del" Method="KH_Del">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KH_Ins" Method="KH_Ins">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ema" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KH_Sel" Method="KH_Sel">
    <ElementType Name="KH_SelResult">
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.KH_Up" Method="KH_Up">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ema" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.khachHang_search" Method="khachHang_search">
    <Parameter Name="tenKH" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="khachHang_searchResult">
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NCC_Del" Method="NCC_Del">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NCC_FindAddress" Method="NCC_FindAddress">
    <Parameter Name="address" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="NCC_FindAddressResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NCC_FindiD" Method="NCC_FindiD">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="NCC_FindiDResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NCC_FindName" Method="NCC_FindName">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="NCC_FindNameResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NCC_Ins" Method="NCC_Ins">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NCC_Sel" Method="NCC_Sel">
    <ElementType Name="NCC_SelResult">
      <Column Name="maNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NCC_Up" Method="NCC_Up">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NV_Del" Method="NV_Del">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NV_Ins" Method="NV_Ins">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nvl" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ema" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NV_Sel" Method="NV_Sel">
    <ElementType Name="NV_SelResult">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWords" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NV_Up" Method="NV_Up">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nvl" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ema" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PN_Del" Method="PN_Del">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PN_Ins" Method="PN_Ins">
    <Parameter Name="ma" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="manv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ng" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.select_cart" Method="select_cart">
    <Parameter Name="maKH" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="select_cartResult">
      <Column Name="magio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_detailCart" Method="select_detailCart">
    <Parameter Name="maGio" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_detailCartResult">
      <Column Name="masp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maCTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_SP" Method="select_SP">
    <ElementType Name="select_SPResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectCTGio" Method="selectCTGio">
    <Parameter Name="maGio" Type="System.Int32" DbType="Int" />
    <ElementType Name="selectCTGioResult">
      <Column Name="maCTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="magio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.selectTotalPrice" Method="selectTotalPrice">
    <ElementType Name="selectTotalPriceResult">
      <Column Name="a" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemTongTienXuat" Method="ThemTongTienXuat">
    <Parameter Name="MaHDX" Parameter="maHDX" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_SoLuongGio" Method="update_SoLuongGio">
    <Parameter Name="maCTGio" Type="System.Int32" DbType="Int" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thanhTien" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_status_hoadon" Method="update_status_hoadon">
    <Parameter Name="maHDX" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="status" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Product_select" Method="Product_select">
    <ElementType Name="Product_selectResult">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.bill_info" Method="bill_info">
    <Parameter Name="maHdx" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="bill_infoResult">
      <Column Name="maHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thongSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.delete_cart" Method="delete_cart">
    <Parameter Name="maGio" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_soluong" Method="update_soluong">
    <Parameter Name="maSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soLuong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.hdx_insert" Method="hdx_insert">
    <Parameter Name="maHDX" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maNV" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tongTien" Type="System.Double" DbType="Float" />
    <Parameter Name="trangThai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngayBan" Type="System.DateTime" DbType="Date" />
    <Parameter Name="giamGia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.thongKeDoanhThu" Method="thongKeDoanhThu">
    <ElementType Name="thongKeDoanhThuResult">
      <Column Name="thang" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="tien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>